### ISSUE TITLE
atari montezuma's revenge?

### ISSUE THREAD

**Issue by hlsafin** [XuGW-Kevin/DrM#1]
Has this been tested on Montezuma's revenge or Pitfall!, visual hard spare problems with discrete action space?

**Comment by XuGW-Kevin** [comment]
Hi! We're sorry that this work primarily concentrates on continuous control, so it has not been tested on tasks with discrete action space.
However, the three key mechanisms we propose for DrM could well be adapted for discrete action tasks on DQN/Efficient Rainbow algorithms with some adjustments.
