### ISSUE TITLE
benchmark results

### ISSUE THREAD

**Issue by IcarusWizard** [XuGW-Kevin/DrM#5]
Hi, thanks for sharing the great work. I want to compare with DrM on some DMC tasks, especially on Humanoid. Could you please share these results with some json or csv files so that I can load and plot directly. Otherwise, I will have to run your code to produce them.

**Comment by XuGW-Kevin** [comment]
Sorry about that! We could provide results on MetaWorld and Adroit if you wished, but the results on DMC tasks were lost because the server was cleared before we thought of downloading them.

**Comment by IcarusWizard** [comment]
Thanks for your quick answer. It is too bad to hear that. Then I have to skip the comparasion since the time is not enough for me to reproduce the results.
